# Generated by Django 4.1.7 on 2023-06-12 16:53

import accounts.utils.genirite_code
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='code',
            field=models.CharField(default=accounts.utils.genirite_code.genritecode, max_length=12),
        ),
    ]
