# Generated by Django 4.1.7 on 2023-03-05 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_electronic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronic',
            name='image',
            field=models.ImageField(upload_to='electronic/'),
        ),
    ]
