# Generated by Django 4.1.7 on 2023-03-08 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='jewellery_100',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Jewellery_reviews', to='shop.jewellery'),
        ),
    ]
