# Generated by Django 4.1.7 on 2023-03-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_reviews1'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews1',
            name='rate',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
