# Generated by Django 4.1.7 on 2023-03-10 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_reviews1_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews1',
            name='rate',
        ),
    ]
