# Generated by Django 4.1.7 on 2023-03-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='home')),
                ('email_us', models.EmailField(max_length=30)),
                ('about', models.TextField(max_length=1000)),
                ('emails', models.CharField(max_length=30)),
                ('phonse', models.CharField(max_length=30)),
                ('adresse', models.CharField(max_length=30)),
            ],
        ),
    ]
